use `gdf`;

delete from COUNTRY;

insert into COUNTRY (CODE,NAME) values 
('IN','INDIA'),
('GB','UNITED KINGDOM'),
('US','UNITED STATES OF AMERICA');




insert into EMAIL_TEMPLATE  (TEMPLATE_TYPE, FILE) values
('USER_REGISTER','FILE'),
('ACCESS_CONFIRM','FILE'),
('DEEDER_REGISTER','FILE'),
('USER_DEEDER_REGISTER','FILE'),
('NOMINATION_CONFIRM','FILE'),
('USER_AMEND','FILE'),
('DEEDER_AMEND','FILE'),
('BUSINESS_REGISTER','FILE'),
('BUSINESS_AMEND','FILE'),
('GOVERNMENT_REGISTER','FILE'),
('GOVERNMENT_AMEND','FILE'),
('NGO_REGISTER','FILE'),
('NGO_AMEND','FILE'),
('BUSINESS_OFFER','FILE'),
('GOVERNMENT_OFFER','FILE'),
('NGO_OFFER','FILE'),
('CREATE_DEED','FILE'),
('DEEDER_NOTIFY_GOVERNMENT_OFFER','FILE'),
('DEEDER_NOTIFY_BUSINESS_OFFER','FILE'),
('DEEDER_NOTIFY_NGO_OFFER','FILE'),
('PASSWORD_RESET','FILE');








