use `gdf`;

CREATE INDEX EMAIL_IDX ON ACCESS(EMAIL);

CREATE INDEX DEED_IDX ON BUSINESS_OFFER(DEED_ID);

CREATE INDEX DEED_IDX ON GOVERNMENT_OFFER(DEED_ID);

CREATE INDEX DEED_IDX ON NGO_OFFER(DEED_ID);